#Checking this commit if it will succeed in the pipeline
#Checking if everything is working fine
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.6.0
workflows:
  build-test-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          repo: nitesh_test
          dockerfile: ~/project/testingApp/Dockerfile
          path: ~/project/testingApp
          tag: latest,myFirst
