version: 2
jobs:
  build:
    docker:
     - image: circleci/ruby:2.4.1
    steps:
     - checkout
     - run: echo "Run First Time"
  build:
    docker:
     - image: circleci/ruby:2.4.1
    steps:
     - checkout
     - run: echo "Run First Time"
